#
# 여기는 AWS의 CodeDeploy, 배포를 도와주는 공간
#

# CodeDeploy 버전
# 프로젝트 버전이 아니라서, 0.0외에 다른 버전을 사용하면 오류가 발생한다.
version: 0.0
os: linux
files:
  # CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상을 지정한다.
  # 루트 경로(/)를 지정하면 전체 파일을 의미한다.
  - source: /

    # source에서 지정된 파일을 받을 위치
    # 이후 Jar를 실행하는 등은 destination에서 옮긴 파일들로 진행된다.
    destination: /home/ec2-user/app/step2/zip/

    # 기존에 파일이 있으면 덮어쓸지를 결정한다.
    # 현재 yes라고 했으니 파일들을 덮어쓰게 된다.
    overwrite: yes


# CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 한다.
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user


# CodeDeploy 배포 단계에서 실행할 명령어를 지정한다.
# ApplicationStart라는 단계에서, deploy.sh를 ec2-user 권한으로 실행하게 된다.

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user